Compare
beepnl/BEEP pull request #185
Opened 2023-04-13 12:00 UTC by TheDiren

Added clean weight function. Working but there might be still some issues when there are multiple inspections in close distance.
Also add a compare data function, to request mean of multiple hives, but that was more for trying out.
There might be some additions to seeder, etc. which actually are not helpful.
also added some tips to readme.

2023-04-19 06:35 UTC, pvgennip requested changes
This should not be in the readme, since it is branch specific and will later on be merged in other branches

2023-04-19 16:07 UTC, pvgennip approved these changes

2023-04-19 16:07 UTC, pvgennip commented on app/Measurement.php
> +        return ['bv','w_v','weight_kg', 'mean_weight_kg', 'weight_kg_noOutlier', 't_i','t_0','t_1','s_bin_71_122','s_bin_122_173','s_bin_173_224','s_bin_224_276','s_bin_276_327','s_bin_327_378','s_bi
Please remove these, since they will never be present in Flashlog data

2023-04-19 16:07 UTC, pvgennip commented on routes/api.php
Maybe include in default way of getting data, does not have to be a separate function

2023-04-19 16:07 UTC, merged

2023-04-20 08:32 UTC, TheDiren commented
I removed changes in the old app and added the default way of getting data to trello